### PR TITLE
Added entry points

### PR DESCRIPTION
**Pull request by jo-asplin-met-no**
Verified locally like this:

```
cd dev/s-enda/py-mmd-tools/
conda create -y -n testenv python=3.9
conda activate testenv
pip install .
PYTHONPATH=. check_nc -i tests/data/reference_nc.nc
PYTHONPATH=. nc2mmd -i tests/data/reference_nc.nc -o .
PYTHONPATH=. yaml2adoc -o foo.adoc
```

### CODE REVIEW

**Review by johtoblan — APPROVED** [review]
LGTM

**Comment by jo-asplin-met-no** [comment]
No idea why we keep getting **'pyTestCov** _Expected -- Waiting for status to be reported_' !

**Comment by johtoblan** [comment]
@jo-asplin-met-no @mortenwh I have now fixed the pyTestCov hanging issue. The branch protection set for master (main in dmci) is not automatically updated, so we have to update that when we add new tests.

**Comment by mortenwh** [comment]
What do you mean by "The branch protection set for master (main in dmci) is not automatically updated, so we have to update that when we add new tests"? Do we need to update the branch protection?

**Pull request merged**
